vermiculus/sx.el

sx.el, test/test-api.el, test/test-macros.el, test/test-printing.el, test/test-util.el, test/tests.el
This PR has been made to track Travis's reactions to the commits. It's not done quite yet:
=> Test Refactoring

sx-interaction.el, sx-question-list.el, sx-tab.el, sx.el
I was bored, so I refactored our `completing-read` calls into `sx-completing-read`.
Feel free to do those crazier refactorings you were talking about on gitter if you'd like.
=> Tiny improvements

sx-cache.el, sx-encoding.el, sx-load.el, sx-time.el
=> Declare lexical binding on all files

sx-interaction.el, sx-question-list.el, sx-question-mode.el, sx-switchto.el, sx-tab.el
List starred questions with `sx-tab-starred`.
Star and unstar questions with `*` and `C-u *`.
=> Access starred questions

sx-filter.el, sx-question-list.el
=> Issue 15 more info

sx-auth.el, sx-favorites.el, sx-filter.el, sx-inbox.el, sx-networks.el, sx-notify.el, sx-question-list.el, sx-question-mode.el, sx-site.el, sx-tag.el, sx-time.el, sx.el
=> Use defconst instead of defvar where appropriate.

sx-compose.el, sx-request.el, sx-search.el, sx-switchto.el, sx-tag.el, sx.el
Implements a new command, bound to C-c C-q in compose-mode, which inserts tags with completion.
=> Issue 137 tag completion

sx-favorites.el
Created this as a separate PR because I wanted to check on travis
=> Don't use sx-favorites--initialize

sx-question-list.el, sx-question-print.el, sx-question.el, sx.el
=> Customizable sorting

sx-filter.el, test/test-macros.el
This fixes the commenting issue for me. Not the voting. =/
=> Build filter from default

sx-interaction.el, sx-question-mode.el, sx-question.el, sx.el, test/test-util.el
Now `RET` should work on any inbox item. Much more usable!
=> Fix sx-display from inbox

sx.el
I forgot the branch was merged, so I'm just going to merge this into master now. See [this comment](https://github.com/vermiculus/sx.el/pull/228#commitcomment-9324043) on #228.
=> Prune useless progn form

sx-request.el
Amongst other things, this should put an end to whale hunting, malaria,
and issues such as #238, #209 and #206.
=> Fix the universe and make the world right again.

README.org
I would have added these *after* the other badges, but some of the badges are slightly different sizes, so this position looks best. :-)
=> Add MELPA badges to README

sx-button.el, sx-question-list.el, sx-question-print.el, sx-question.el, sx-search.el, sx-tag.el, test/test-printing.el
Tags everywhere are buttons now. In-body tags also render pretty.
Fix #230 and Fix #229
=> Tag buttons

sx-question-mode.el, sx-question-print.el, sx.el
Bound to O
This also added the inverse of the previously defined sorts.
=> Bind answer sorting to a key

sx-question-list.el, sx-question-mode.el, sx.el
More informative mode-line in question-mode
This builds on `small-improvements`.
=> Question mode line

sx-question-list.el, sx-question-mode.el, sx.el
Automate header-line definition from the keymap
=> Generate header line from keymap

sx-question-print.el
Indicate closed questions. Builds on `delete-command`
=> Closed questions

sx-compose.el, sx-interaction.el
- Don't let the user start composing stuff if they're not authenticated.
- If something goes wrong when sending a question, don't delete the header.
=> Issue 271  asking vs auth

README.org, sx-question-list.el, sx-search.el, sx-tab.el, test/test-printing.el
=> More ordering

sx-question-print.el, test/test-printing.el
Completely rewrote this PR. It was a mess of a merge so it was easier to just start from scratch.
=> Better printing
